tec_db = 'CLARO_IN_HFC'
tec_db_table = 'DEV_TEMP_CZ_TEC'
# tec_db_table = 'TEMP_CZ_TEC_V2'
tec_maxColNumber = 124
tec_xl_colNameRow = 4
tec_xl_firstDataRow = tec_xl_colNameRow + 1
tec_xl_colCheckFlag = 'D'  # verifica si existe data en esa columna, si no encuentra finaliza el loop de registro de evas
tec_xl_hoja = 'DATA'  # Nombre de la hoja donde se encuentra la data

tec = [
    {'colName': 'CANTIDAD TOTAL ', 'col': 'A', 'sqlName': 'CANTIDAD TOTAL ', 'tipo': 'default'},
    {'colName': 'SEMANA', 'col': 'B', 'sqlName': 'SEMANA', 'tipo': 'default'},
    {'colName': 'N° DE INFORME', 'col': 'C', 'sqlName': 'N° DE INFORME', 'tipo': 'default'},
    {'colName': 'CODIGO DEL ASESOR', 'col': 'D', 'sqlName': 'CODIGO DEL ASESOR', 'tipo': 'default'},
    {'colName': 'NOMBRE DEL ASESOR', 'col': 'E', 'sqlName': 'NOMBRE DEL ASESOR', 'tipo': 'default'},
    {'colName': 'CONEXIÓN ', 'col': 'F', 'sqlName': 'CONEXIÓN ', 'tipo': 'default'},
    {'colName': 'ANTIGÜEDAD AGENTE', 'col': 'G', 'sqlName': 'ANTIGÜEDAD AGENTE', 'tipo': 'default'},
    {'colName': 'CAMPAÑA', 'col': 'H', 'sqlName': 'CAMPAÑA', 'tipo': 'default'},
    {'colName': 'PROVEEDOR', 'col': 'I', 'sqlName': 'PROVEEDOR', 'tipo': 'default'},
    {'colName': 'FECHA DE MONITOREO', 'col': 'J', 'sqlName': 'FECHA DE MONITOREO', 'tipo': 'default'},
    {'colName': 'SN - IPCC', 'col': 'K', 'sqlName': 'SN - IPCC', 'tipo': 'no_duplicado'},
    {'colName': 'FECHA DE LA LLAMADA', 'col': 'L', 'sqlName': 'FECHA DE LA LLAMADA', 'tipo': 'default'},
    {'colName': 'HORA DE LA LLAMADA', 'col': 'M', 'sqlName': 'HORA DE LA LLAMADA', 'tipo': 'default'},
    {'colName': 'TMG', 'col': 'N', 'sqlName': 'TMG', 'tipo': 'default'},
    {'colName': 'TMG MONITOREO', 'col': 'O', 'sqlName': 'TMG MONITOREO', 'tipo': 'default'},
    {'colName': 'NOMBRE DEL CLIENTE', 'col': 'P', 'sqlName': 'NOMBRE DEL CLIENTE', 'tipo': 'default'},
    {'colName': 'N° TELF DEL QUE LLLAMA (MSISDN)', 'col': 'Q', 'sqlName': 'N° TELF DEL QUE LLLAMA MSISDN', 'tipo': 'str'},
    {'colName': ' NÚMERO IDENTIFICADO (TELEFONO EN CONSULTA)', 'col': 'R', 'sqlName': 'NUMERO IDENTIFICADO TELEFONO EN CONSULTA', 'tipo': 'str'},
    {'colName': 'TIPO DE LLAMADA', 'col': 'S', 'sqlName': 'TIPO DE LLAMADA', 'tipo': 'default'},
    {'colName': 'MOTIVO DE LLAMADA', 'col': 'T', 'sqlName': 'MOTIVO DE LLAMADA', 'tipo': 'default'},
    {'colName': 'SUBMOTIVO DE LLAMADA', 'col': 'U', 'sqlName': 'SUBMOTIVO DE LLAMADA', 'tipo': 'default'},
    {'colName': 'MOTIVO DE LLAMADA 2', 'col': 'V', 'sqlName': 'MOTIVO DE LLAMADA 2', 'tipo': 'default'},
    {'colName': 'SUBMOTIVO DE LLAMADA 2', 'col': 'W', 'sqlName': 'SUBMOTIVO DE LLAMADA 2', 'tipo': 'default'},
    {'colName': 'DESCRIPCIÓN DE LA LLAMADA', 'col': 'X', 'sqlName': 'DESCRIPCIÓN DE LA LLAMADA', 'tipo': 'default'},
    {'colName': 'TIPIFICAICON  AGENTE SIAC', 'col': 'Y', 'sqlName': 'TIPIFICAICON AGENTE SIAC', 'tipo': 'default'},
    {'colName': 'SERVICIO AFECTADO', 'col': 'Z', 'sqlName': 'SERVICIO AFECTADO', 'tipo': 'default'},
    {'colName': 'DETALLE DEL INCONVENIENTE', 'col': 'AA', 'sqlName': 'DETALLE DEL INCONVENIENTE', 'tipo': 'default'},
    {'colName': 'LA LLAMADA ES REINCIDENCIA', 'col': 'AB', 'sqlName': 'LA LLAMADA ES REINCIDENCIA', 'tipo': 'default'},
    {'colName': 'INDICÓ EL NOMBRE DEL CLIENTE EN EL SALUDO', 'col': 'AC', 'sqlName': 'INDICO EL NOMBRE DEL CLIENTE EN EL SALUDO', 'tipo': 'default'},
    {'colName': 'PIDIÓ EL NÚMERO EN CONSULTA (MÓVIL) O DOCUMENTO DE IDENTIDAD (FIJA) PARA IDENTIFICAR EL SERVICIO', 'col': 'AD', 'sqlName': 'PIDIO EL NÚMERO EN CONSULTA O DOCUMENTO DE IDENTIDAD', 'tipo': 'default'},
    {'colName': 'ALERTA POSIBLE MALA DICCIÓN', 'col': 'AE', 'sqlName': 'ALERTA POSIBLE MALA DICCION', 'tipo': 'default'},
    {'colName': 'ALERTA DE POSIBLE INDOLENCIA EN LA ATENCIÓN', 'col': 'AF', 'sqlName': 'ALERTA DE POSIBLE INDOLENCIA EN LA ATENCION', 'tipo': 'default'},
    {'colName': 'ASESOR CONTABA CON PROCESO ADECUADO PARA ATENCIÓN', 'col': 'AG', 'sqlName': 'ASESOR CONTABA CON PROCESO ADECUADO PARA ATENCION', 'tipo': 'default'},
    {'colName': 'NOMBRE DEL MONITOREADOR O RESPONSABLE DEL MONITOREO', 'col': 'AH', 'sqlName': 'NOMBRE DEL MONITOREADOR O RESPONSABLE DEL MONITOREO', 'tipo': 'default'},
    {'colName': '1.1 Saluda conforme a lo indicado en el Lineamiento de Atención ', 'col': 'AI', 'sqlName': '1#1 Saluda conforme a lo indicado en el Lineamiento de Atención', 'tipo': 'default'},
    {'colName': '1.1.1 Inmediatamente ingresa la llamada', 'col': 'AJ', 'sqlName': '1#1#1 Inmediatamente ingresa la llamada', 'tipo': 'default'},
    {'colName': '1.1.2 Aplica saludo de bienvenida', 'col': 'AK', 'sqlName': '1#1#2 Aplica saludo de bienvenida', 'tipo': 'default'},
    {'colName': '1.1.3 Presentación del AS con nombre y apellido', 'col': 'AL', 'sqlName': '1#1#3 Presentación del AS con nombre y apellido', 'tipo': 'default'},
    {'colName': '1.1.4 Menciona el nombre del cliente', 'col': 'AM', 'sqlName': '1#1#4 Menciona el nombre del cliente', 'tipo': 'default'},
    {'colName': ' 1. Bienvenida', 'col': 'AN', 'sqlName': 'PONDERACION_1', 'tipo': 'cf'},
    {'colName': '2.1 Solo si no es clara la necesidad (información, preocupación, problema), reconfirma, realiza una pregunta de precisión y/o aclara sin criticar o corregir negativamente al cliente', 'col': 'AO', 'sqlName': '2#1 Solo si no es clara la necesidad', 'tipo': 'default'},
    {'colName': '2.2 Diagnostica correctamente la necesidad', 'col': 'AP', 'sqlName': '2#2 Diagnostica correctamente la necesidad', 'tipo': 'default'},
    {'colName': '2.3 Evita ser negativo ante la necesidad expuesta', 'col': 'AQ', 'sqlName': '2#3 Evita ser negativo ante la necesidad expuesta', 'tipo': 'default'},
    {'colName': '2.3.1 Sin poner en duda lo expuesto por el cliente', 'col': 'AR', 'sqlName': '2#3#1 Sin poner en duda lo expuesto por el cliente', 'tipo': 'default'},
    {'colName': '2.3.2 Sin hacerlo sentir menos por no entender o saber', 'col': 'AS', 'sqlName': '2#3#2 Sin hacerlo sentir menos por no entender o saber', 'tipo': 'default'},
    {'colName': '2.3.3 Sin hacerlo sentir responsable del problema que pudo haber ocasionado en el servicio', 'col': 'AT', 'sqlName': '2#3#3 Sin hacerlo sentir responsable del problema que pudo haber', 'tipo': 'default'},
    {'colName': '2.4 Evita realizar validaciones innecesarias', 'col': 'AU', 'sqlName': '2#4 Evita realizar validaciones innecesarias', 'tipo': 'default'},
    {'colName': '2.4.1 Datos de titularidad', 'col': 'AV', 'sqlName': '2#4#1 Datos de titularidad', 'tipo': 'default'},
    {'colName': '2.4.2 Datos del servicio que figuran en el sistema', 'col': 'AW', 'sqlName': '2#4#2 Datos del servicio que figuran en el sistema', 'tipo': 'default'},
    {'colName': '2.4.3 Datos que ya fueron brindados por el cliente', 'col': 'AX', 'sqlName': '2#4#3 Datos que ya fueron brindados por el cliente', 'tipo': 'default'},
    {'colName': '2.5 De acuerdo con lo expuesto por el cliente y/o por lo revisado en sistemas, confirma con el cliente que existe alguna atención previa por el mismo motivo.', 'col': 'AY', 'sqlName': '2#5 De acuerdo con lo expuesto por el cliente y_o por lo revisad', 'tipo': 'default'},
    {'colName': ' 2. Diagnóstico de la necesidad', 'col': 'AZ', 'sqlName': 'PONDERACION_2', 'tipo': 'cf'},
    {'colName': '3.1 Brinda información completa de acuerdo a la necesidad del cliente, incluido el número de caso/interacción según corresponda. Ante falta de información de proceso, escala con supervisor.', 'col': 'BA', 'sqlName': '3#1 Brinda información completa de acuerdo a la necesidad del cl', 'tipo': 'default'},
    {'colName': 'Motivo de consulta 1 (en caso de mala información, especificar el o los motivos)', 'col': 'BB', 'sqlName': 'Motivo de consulta 1 3#1', 'tipo': 'default'},
    {'colName': 'Motivo de consulta 2(en caso de mala información, especificar el o los motivos)', 'col': 'BC', 'sqlName': 'Motivo de consulta 2 3#1', 'tipo': 'default'},
    {'colName': '3.2 Realiza los descartes y pasos de acuerdo a lo establecido en el procedimiento', 'col': 'BD', 'sqlName': '3#2 Realiza los descartes y pasos de acuerdo a lo establecido en', 'tipo': 'default'},
    {'colName': ' Motivo de Consulta 1(en caso de no realizarlo, especificar el o los motivos)', 'col': 'BE', 'sqlName': 'Motivo de Consulta 1 3#2', 'tipo': 'default'},
    {'colName': ' Motivo de Consulta 2(en caso de no realizarlo, especificar el o los motivos)', 'col': 'BF', 'sqlName': 'Motivo de Consulta 2 3#2', 'tipo': 'default'},
    {'colName': '3.3 Registra la gestión', 'col': 'BG', 'sqlName': '3#3 Registra la gestión', 'tipo': 'default'},
    {'colName': '3.3.1 Tipifica todas las consultas', 'col': 'BH', 'sqlName': '3#3#1 Tipifica todas las consultas', 'tipo': 'default'},
    {'colName': '3.3.2 La tipificación utilizada es la correcta', 'col': 'BI', 'sqlName': '3#3#2 La tipificación utilizada es la correcta', 'tipo': 'default'},
    {'colName': '3.3.3 Las notas y/o plantillas de la tipificación son correctas. ', 'col': 'BJ', 'sqlName': '3#3#3 Las notas y_o plantillas de la tipificación son correctas#', 'tipo': 'default'},
    {'colName': ' 3. Solución Efectiva', 'col': 'BK', 'sqlName': 'PONDERACION_3', 'tipo': 'cf'},
    {'colName': '4.1 Consulta al cliente si entendió la gestión o explicación brindada', 'col': 'BL', 'sqlName': '4#1 Consulta al cliente si entendió la gestión o explicación bri', 'tipo': 'default'},
    {'colName': '4.2 En caso de dudas las clarifica de forma adecuada asegurando el entendimiento del cliente', 'col': 'BM', 'sqlName': '4#2 En caso de dudas las clarifica de forma adecuada asegurando ', 'tipo': 'default'},
    {'colName': '4.3 Si la solución no es en línea, refuerza que se atenderá su necesidad', 'col': 'BN', 'sqlName': '4#3 Si la solución no es en línea refuerza que se atenderá su n', 'tipo': 'default'},
    {'colName': ' 4. Validación de la Solución', 'col': 'BO', 'sqlName': 'PONDERACION_4', 'tipo': 'cf'},
    {'colName': '5.1 Realiza recomendaciones de Valor', 'col': 'BP', 'sqlName': '5#1 Realiza recomendaciones de Valor', 'tipo': 'default'},
    {'colName': ' (Indicar recomendación realizada)', 'col': 'BQ', 'sqlName': 'Recomendación realizada 5#1', 'tipo': 'default'},
    {'colName': '5.2 Realiza recomendaciones Comerciales', 'col': 'BR', 'sqlName': '5#2 Realiza recomendaciones Comerciales', 'tipo': 'default'},
    {'colName': ' (Indicar recomendación realizada)2', 'col': 'BS', 'sqlName': 'Recomendación realizada 5#2', 'tipo': 'default'},
    {'colName': ' 5. Recomendación', 'col': 'BT', 'sqlName': 'PONDERACION_5', 'tipo': 'cf'},
    {'colName': '6.1 Informa al cliente que buscamos mejorar cada vez más la experiencia que damos a nuestros clientes ', 'col': 'BU', 'sqlName': '6#1 Informa al cliente que buscamos mejorar cada vez más la expe', 'tipo': 'default'},
    {'colName': '6.2 Informa de manera clara al cliente  que será derivado a una encuesta ', 'col': 'BV', 'sqlName': '6#2 Informa de manera clara al cliente  que será derivado a una ', 'tipo': 'default'},
    {'colName': '6.2.1  Sin mencionar una escala en particular', 'col': 'BW', 'sqlName': '6#2#1 Sin mencionar una escala en particular', 'tipo': 'default'},
    {'colName': '6.3 Agradece al cliente por la espera y demoras generadas en la llamada', 'col': 'BX', 'sqlName': '6#3 Agradece al cliente por la espera y demoras generadas en la ', 'tipo': 'default'},
    {'colName': '6.4 La despedida es de manera natural y fluida', 'col': 'BY', 'sqlName': '6#4 La despedida es de manera natural y fluida', 'tipo': 'default'},
    {'colName': ' 6. Finalizar Experiencia', 'col': 'BZ', 'sqlName': 'PONDERACION_6', 'tipo': 'cf'},
    {'colName': '7.1 Se dirige al cliente por su nombre utilizando el “Usted” durante el transcurso de la llamada', 'col': 'CA', 'sqlName': '7#1 Se dirige al cliente por su nombre utilizando el Usted', 'tipo': 'default'},
    {'colName': '7.2 Evita utilizar términos no permitidos en el Lineamiento de Atención', 'col': 'CB', 'sqlName': '7#2 Evita utilizar términos no permitidos en el Lineamiento', 'tipo': 'default'},
    {'colName': '7.2.1 Caballero/joven u otro no solicitado expresamente.', 'col': 'CC', 'sqlName': '7#2#1 Caballero_joven u otro no solicitado expresamente', 'tipo': 'default'},
    {'colName': '7.2.2 Política o religión, excepto si el cliente hace una referencia inicial', 'col': 'CD', 'sqlName': '7#2#2 Política o religión excepto si el cliente hace una refere', 'tipo': 'default'},
    {'colName': '7.3 Se expresa con entusiasmo durante la llamada', 'col': 'CE', 'sqlName': '7#3 Se expresa con entusiasmo durante la llamada', 'tipo': 'default'},
    {'colName': '7.4 Se expresa con naturalidad durante la llamada', 'col': 'CF', 'sqlName': '7#4 Se expresa con naturalidad durante la llamada', 'tipo': 'default'},
    {'colName': '7.5 Escucha atentamente al cliente ', 'col': 'CG', 'sqlName': '7#5 Escucha atentamente al cliente', 'tipo': 'default'},
    {'colName': '7.5.1 Sin interrumpir abruptamente', 'col': 'CH', 'sqlName': '7#5#1 Sin interrumpir abruptamente', 'tipo': 'default'},
    {'colName': '7.5.2 Sin realizar suposiciones antes que el cliente termine de hablar o explicar', 'col': 'CI', 'sqlName': '7#5#2 Sin realizar suposiciones antes que el cliente termine', 'tipo': 'default'},
    {'colName': '7.6 Según la o las situaciones expuestas por el cliente, empatiza utilizando frases relacionadas a la situación', 'col': 'CJ', 'sqlName': '7#6 Segun la o las situaciones expuestas por el cliente empatiz', 'tipo': 'default'},
    {'colName': '7.6.1 De forma natural', 'col': 'CK', 'sqlName': '7#6#1 De forma natural', 'tipo': 'default'},
    {'colName': '7.6.2 Tono de voz transmite emociones', 'col': 'CL', 'sqlName': '7#6#2 Tono de voz transmite emociones', 'tipo': 'default'},
    {'colName': '7.6.3 Transmite interés y preocupación', 'col': 'CM', 'sqlName': '7#6#3 Transmite interés y preocupación', 'tipo': 'default'},
    {'colName': '7.7 Interactúa con el cliente', 'col': 'CN', 'sqlName': '7#7 Interactúa con el cliente', 'tipo': 'default'},
    {'colName': '7.7.1 Informa al cliente las acciones que está realizando', 'col': 'CO', 'sqlName': '7#7#1 Informa al cliente las acciones que está realizando', 'tipo': 'default'},
    {'colName': '7.7.2 Evita usar locución de espera (hold), salvo necesidad justificada e informada al cliente', 'col': 'CP', 'sqlName': '7#7#2 Evita usar locución de espera hold salvo necesidad', 'tipo': 'default'},
    {'colName': '7.8 Evita realizar comentarios negativos sobre Claro. ', 'col': 'CQ', 'sqlName': '7#8 Evita realizar comentarios negativos sobre Claro', 'tipo': 'default'},
    {'colName': ' 7. Actitud en toda la atención', 'col': 'CR', 'sqlName': 'PONDERACION_7', 'tipo': 'cf'},
    {'colName': 'CALIFICACIÓN FINAL', 'col': 'CY', 'sqlName': 'SUB - CALIFICACIÓN', 'tipo': 'cf'},
    {'colName': 'ERRORES CRITICOS DE USUARIO FINAL', 'col': 'CT', 'sqlName': 'ERRORES CRITICOS DE USUARIO FINAL', 'tipo': 'default'},
    {'colName': 'ERRORES CRITICOS DE NEGOCIO', 'col': 'CU', 'sqlName': 'ERRORES CRITICOS DE NEGOCIO', 'tipo': 'default'},
    {'colName': 'ERRORES CRITICOS DE CUMPLIMIENTO', 'col': 'CV', 'sqlName': 'ERRORES CRITICOS DE CUMPLIMIENTO', 'tipo': 'default'},
    {'colName': 'TOTAL ERRORES CRITICOS', 'col': 'CW', 'sqlName': 'TOTAL ERRORES CRITICOS', 'tipo': 'default'},
    {'colName': 'TOTAL ERRORES NO CRITICOS', 'col': 'CX', 'sqlName': 'TOTAL ERRORES NO CRITICOS', 'tipo': 'default'},
    {'colName': 'CALIFICACIÓN FINAL', 'col': 'CY', 'sqlName': 'CALIFICACIÓN FINAL', 'tipo': 'cf'},
    {'colName': 'AS induce al cliente a cortar la llamada por dejarlo en espera por tiempo prolongado', 'col': 'CZ', 'sqlName': 'AS induce al cliente a cortar la llamada por dejarlo en espera p', 'tipo': 'default'},
    {'colName': 'AS transfiere a cualquier locución cuando aún no ha concluido con la atención ', 'col': 'DA', 'sqlName': 'AS transfiere a cualquier locución cuando aún no ha concluido co', 'tipo': 'default'},
    {'colName': 'AS transfiere a locución de vicio,  IVR de Campañas (cabecera), Skill u otro nivel que no corresponde', 'col': 'DB', 'sqlName': 'AS transfiere a locución de vicio IVR de Campañas', 'tipo': 'default'},
    {'colName': 'AS se dirige en la llamada mencionando palabras soeces.', 'col': 'DC', 'sqlName': 'AS se dirige en la llamada mencionando palabras soeces', 'tipo': 'default'},
    {'colName': 'AS se dirige al cliente con mala actitud y/o con sarcasmo.', 'col': 'DD', 'sqlName': 'AS se dirige al cliente con mala actitud y_o con sarcasmo', 'tipo': 'default'},
    {'colName': 'AS conversa con un tercero o hace ruidos molestos (sonidos, golpes, risas, etc.) durante la atención', 'col': 'DE', 'sqlName': 'AS conversa con un tercero o hace ruidos molestos', 'tipo': 'default'},
    {'colName': 'AS no cuenta con una diccion correcta en la atencion ', 'col': 'DF', 'sqlName': 'AS no cuenta con una diccion correcta en la atencion', 'tipo': 'default'},
    {'colName': 'AS deriva a otro canal cuando la atencion no lo amerita', 'col': 'DG', 'sqlName': 'AS deriva a otro canal cuando la atencion no lo amerita', 'tipo': 'default'},
    {'colName': 'COMENTARIO  MALA PRÁCTICA', 'col': 'DH', 'sqlName': 'COMENTARIO MALA PRÁCTICA', 'tipo': 'default'},
    {'colName': 'FCR', 'col': 'DI', 'sqlName': 'FCR', 'tipo': 'default'},
    {'colName': 'RESPONSABILIDAD DE NO FCR', 'col': 'DJ', 'sqlName': 'RESPONSABILIDAD DE NO FCR', 'tipo': 'default'},
    {'colName': 'MOTIVO DE NO FCR', 'col': 'DK', 'sqlName': 'MOTIVO DE NO FCR', 'tipo': 'default'},
    {'colName': 'PROCESO CLARO NO FCR', 'col': 'DL', 'sqlName': 'PROCESO CLARO NO FCR', 'tipo': 'default'},
    {'colName': 'DETALLE DE NO FCR', 'col': 'DM', 'sqlName': 'DETALLE DE NO FCR', 'tipo': 'default'},
    {'colName': 'ACCION QUE REALIZA EL ASESOR', 'col': 'DN', 'sqlName': 'ACCION QUE REALIZA EL ASESOR', 'tipo': 'default'},
    {'colName': 'TIENE ALARMA', 'col': 'DO', 'sqlName': 'TIENE ALARMA', 'tipo': 'default'},
    {'colName': 'OBSERVACION / RECOMENDACIÓN', 'col': 'DP', 'sqlName': 'OBSERVACION_RECOMENDACION', 'tipo': 'default'},
    {'colName': 'LLAMADA ES CON AUDIO O VIDEO ', 'col': 'DQ', 'sqlName': 'LLAMADA ES CON AUDIO O VIDEO', 'tipo': 'default'},
    {'colName': 'Diagnostico', 'col': 'DR', 'sqlName': 'DIAGNOSTICO', 'tipo': 'default'}
]