webboreclamos_db = 'DEV_Ricardo'
webboreclamos_db_table = 'TB_BO_RECLAMOS_TEST'
webboreclamos_maxColNumber = 268
webboreclamos_xl_colNameRow = 1
webboreclamos_xl_firstDataRow = webboreclamos_xl_colNameRow + 1
webboreclamos_xl_colCheckFlag = 'A'  # verifica si existe data en esa columna, si no encuentra finaliza el loop de registro de evas
webboreclamos_xl_hoja = 'Sheet'  # Nombre de la hoja donde se encuentra la data

webboreclamos = [
    {'colName': 'ID', 'col': 'A', 'sqlName': 'ID', 'tipo': 'default'},
    {'colName': 'FECHA_INICIAL', 'col': 'B', 'sqlName': 'FECHA_INICIAL', 'tipo': 'str_to_datetime_webevas'},
    {'colName': 'FECHA_INI', 'col': 'C', 'sqlName': 'FECHA_INI', 'tipo': 'str_to_datetime_webevas'},
    {'colName': 'FECHA_FIN', 'col': 'D', 'sqlName': 'FECHA_FIN', 'tipo': 'str_to_datetime_webevas'},
    {'colName': 'CBO_ESTADO', 'col': 'E', 'sqlName': 'CBO_ESTADO', 'tipo': 'default'},
    {'colName': 'NIVEL_1', 'col': 'F', 'sqlName': 'NIVEL_1', 'tipo': 'default'},
    {'colName': 'NIVEL_2', 'col': 'G', 'sqlName': 'NIVEL_2', 'tipo': 'default'},
    {'colName': 'NIVEL_3', 'col': 'H', 'sqlName': 'NIVEL_3', 'tipo': 'default'},
    {'colName': 'NIVEL_4', 'col': 'I', 'sqlName': 'NIVEL_4', 'tipo': 'default'},
    {'colName': 'NIVEL_5', 'col': 'J', 'sqlName': 'NIVEL_5', 'tipo': 'default'},
    {'colName': 'TXT_OBSERVACION', 'col': 'K', 'sqlName': 'TXT_OBSERVACION', 'tipo': 'default'},
    {'colName': 'DNI_USUARIO', 'col': 'L', 'sqlName': 'DNI_USUARIO', 'tipo': 'default'},
    {'colName': 'TxtCodigoAsesor', 'col': 'M', 'sqlName': 'TxtCodigoAsesor', 'tipo': 'default'},
    {'colName': 'TxtNombreAsesor', 'col': 'N', 'sqlName': 'TxtNombreAsesor', 'tipo': 'default'},
    {'colName': 'TxtCampania', 'col': 'O', 'sqlName': 'TxtCampania', 'tipo': 'default'},
    {'colName': 'MotivoLLamada', 'col': 'P', 'sqlName': 'MotivoLLamada', 'tipo': 'default'},
    {'colName': 'FinalGestion', 'col': 'Q', 'sqlName': 'FinalGestion', 'tipo': 'default'},
    {'colName': 'DNI_AGENTE', 'col': 'R', 'sqlName': 'DNI_AGENTE', 'tipo': 'default'},
    {'colName': 'IDGestion', 'col': 'S', 'sqlName': 'IDGestion', 'tipo': 'default'},
    {'colName': 'FechaMonitoreo', 'col': 'T', 'sqlName': 'FechaMonitoreo', 'tipo': 'default'},
    {'colName': 'TipoMonitoreo', 'col': 'U', 'sqlName': 'TipoMonitoreo', 'tipo': 'default'},
    {'colName': 'SN', 'col': 'V', 'sqlName': 'SN', 'tipo': 'default'},
    {'colName': 'FechaLLamada', 'col': 'W', 'sqlName': 'FechaLLamada', 'tipo': 'default'},
    {'colName': 'HoraLLamada', 'col': 'X', 'sqlName': 'HoraLLamada', 'tipo': 'default'},
    {'colName': 'TMG', 'col': 'Y', 'sqlName': 'TMG', 'tipo': 'default'},
    {'colName': 'NombreCliente', 'col': 'Z', 'sqlName': 'NombreCliente', 'tipo': 'default'},
    {'colName': 'NumeroTelefonoConsulta', 'col': 'AA', 'sqlName': 'NumeroTelefonoConsulta', 'tipo': 'default'},
    {'colName': 'NumeroCaso', 'col': 'AB', 'sqlName': 'NumeroCaso', 'tipo': 'default'},
    {'colName': 'DescripcionLLamada', 'col': 'AC', 'sqlName': 'DescripcionLLamada', 'tipo': 'default'},
    {'colName': 'TxtOBSERVACIONES', 'col': 'AD', 'sqlName': 'TxtOBSERVACIONES', 'tipo': 'default'},
    {'colName': 'CAMPO_1_1', 'col': 'AE', 'sqlName': 'CAMPO_1_1', 'tipo': 'default'},
    {'colName': 'CAMPO_1_2', 'col': 'AF', 'sqlName': 'CAMPO_1_2', 'tipo': 'default'},
    {'colName': 'CAMPO_1_3', 'col': 'AG', 'sqlName': 'CAMPO_1_3', 'tipo': 'default'},
    {'colName': 'CAMPO_1_4', 'col': 'AH', 'sqlName': 'CAMPO_1_4', 'tipo': 'default'},
    {'colName': 'CAMPO_2_1', 'col': 'AI', 'sqlName': 'CAMPO_2_1', 'tipo': 'default'},
    {'colName': 'CAMPO_2_2', 'col': 'AJ', 'sqlName': 'CAMPO_2_2', 'tipo': 'default'},
    {'colName': 'CAMPO_3_1', 'col': 'AK', 'sqlName': 'CAMPO_3_1', 'tipo': 'default'},
    {'colName': 'CAMPO_3_2', 'col': 'AL', 'sqlName': 'CAMPO_3_2', 'tipo': 'default'},
    {'colName': 'CAMPO_3_3', 'col': 'AM', 'sqlName': 'CAMPO_3_3', 'tipo': 'default'},
    {'colName': 'CAMPO_4_1', 'col': 'AN', 'sqlName': 'CAMPO_4_1', 'tipo': 'default'},
    {'colName': 'CAMPO_4_2', 'col': 'AO', 'sqlName': 'CAMPO_4_2', 'tipo': 'default'},
    {'colName': 'CAMPO_4_3', 'col': 'AP', 'sqlName': 'CAMPO_4_3', 'tipo': 'default'},
    {'colName': 'CAMPO_4_4', 'col': 'AQ', 'sqlName': 'CAMPO_4_4', 'tipo': 'default'},
    {'colName': 'CAMPO_4_5', 'col': 'AR', 'sqlName': 'CAMPO_4_5', 'tipo': 'default'},
    {'colName': 'CAMPO_4_6', 'col': 'AS', 'sqlName': 'CAMPO_4_6', 'tipo': 'default'},
    {'colName': 'CAMPO_4_7', 'col': 'AT', 'sqlName': 'CAMPO_4_7', 'tipo': 'default'},
    {'colName': 'CAMPO_5_1', 'col': 'AU', 'sqlName': 'CAMPO_5_1', 'tipo': 'default'},
    {'colName': 'CAMPO_5_2', 'col': 'AV', 'sqlName': 'CAMPO_5_2', 'tipo': 'default'},
    {'colName': 'CAMPO_5_3', 'col': 'AW', 'sqlName': 'CAMPO_5_3', 'tipo': 'default'},
    {'colName': 'CAMPO_5_4', 'col': 'AX', 'sqlName': 'CAMPO_5_4', 'tipo': 'default'},
    {'colName': 'STATUS', 'col': 'AY', 'sqlName': 'STATUS', 'tipo': 'default'},
    {'colName': 'TXT_PEDIDO_ASOCIADO', 'col': 'AZ', 'sqlName': 'TXT_PEDIDO_ASOCIADO', 'tipo': 'default'},
    {'colName': 'ID_CARGA', 'col': 'BA', 'sqlName': 'ID_CARGA', 'tipo': 'default'},
    {'colName': 'TIPORECLAMO', 'col': 'BB', 'sqlName': 'TIPORECLAMO', 'tipo': 'default'},
    {'colName': 'AGENTE', 'col': 'BC', 'sqlName': 'USUARIO', 'tipo': 'default'},
]
